// Generated by CoffeeScript 1.3.3
var derby, express, expressApp, hello, http, server, store;

http = require('http');

express = require('express');

derby = require('derby');

hello = require('./hello');

expressApp = express();

server = http.createServer(expressApp);

store = derby.createStore({
  listen: server
});

expressApp.use(express["static"](__dirname + '/public')).use(store.modelMiddleware()).use(hello.router());

server.listen(3000);
