// Generated by CoffeeScript 1.3.1
var express, expressApp, hello, http, server, store;

http = require('http');

express = require('express');

hello = require('./hello');

store = hello.createStore();

expressApp = express().use(express["static"](__dirname + '/public')).use(store.modelMiddleware()).use(hello.router());

server = http.createServer(expressApp).listen(3000);

store.listen(server);
